"""Package one tally-agent release for upload (run by .github/workflows/agent-release.yml).

    python tally-agent/tools/release.py --version 1.2.3 --publish-dir out/publish \
        --scripts-dir tally-agent --out-dir out/release

Writes into --out-dir:
    tally-agent-<ver>.zip   publish/** + install.ps1 + uninstall.ps1
                            (appsettings*.json and *.pdb are left out: the per-shop
                            config is generated by the backend, and an update must
                            never overwrite a shop's key)
    pending.json            {version, sha256, size_bytes, zip_key, built_at, git_sha}

CI does NOT sign and holds no signing key. A human on the VPS reviews this release and
signs it (`docker exec -it metalerp-api python -m tools.agent_release sign <ver>`,
api/tools/agent_release.py). Until then the API cannot see the release
(it reads release.json / latest.json only), so an uploaded-but-unsigned build
reaches nobody.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import zipfile
from datetime import UTC, datetime
from pathlib import Path

VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
SCRIPTS = ("install.ps1", "uninstall.ps1")


def build_zip(publish_dir: Path, scripts_dir: Path, zip_path: Path) -> None:
    if not (publish_dir / "TallyAgent.exe").is_file():
        sys.exit(f"{publish_dir} has no TallyAgent.exe - publish first")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(publish_dir.rglob("*")):
            if not f.is_file():
                continue
            rel = f.relative_to(publish_dir).as_posix()
            name = f.name.lower()
            if name.startswith("appsettings") or name.endswith(".pdb"):
                continue
            z.write(f, f"publish/{rel}")
        for s in SCRIPTS:
            z.write(scripts_dir / s, s)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--publish-dir", type=Path, required=True)
    ap.add_argument("--scripts-dir", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, required=True)
    a = ap.parse_args()

    if not VERSION_RE.match(a.version):
        sys.exit(f"version must look like 1.2.3, got {a.version!r}")
    a.out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = a.out_dir / f"tally-agent-{a.version}.zip"
    build_zip(a.publish_dir, a.scripts_dir, zip_path)

    data = zip_path.read_bytes()
    pending = {
        "version": a.version,
        "sha256": hashlib.sha256(data).hexdigest(),
        "size_bytes": len(data),
        "zip_key": f"agent-releases/{a.version}/{zip_path.name}",
        "built_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "git_sha": os.environ.get("GITHUB_SHA", ""),
    }
    (a.out_dir / "pending.json").write_text(json.dumps(pending, indent=2))
    print(json.dumps(pending, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
